### ISSUE TITLE
Problem with OTAA registration

### ISSUE THREAD

**Issue by jw35** [SmartCambridge/tfc_web#277]
There seem to be two related problems registering devices with OTAA:

1) In a client, an OTAA registration needs a `Dev EUI`, an `App EUI` and and `App Key`. On the CSN device page you get to supply and/or generate a Dev EUI and an App Key, but there's no reference to an App EUI. In the current config where everything is routed to the SmartCambridge feedmaker you need to know  somehow to use `28e8280872db83d3`. In the future where we will have made each use their own Filter/Connection pair you'll need some way to supply whatever App EUI the filter is using.

2) The App Key that you supply or generate never turns up on the Everynet console. This may be because created devices have an 'Encryption' setting of 'App'. 

![image](https://user-images.githubusercontent.com/2385623/51553523-f8243580-1e6a-11e9-857b-7b2487c8bc56.png)

Manually switching this to 'NS' causes a 'Application Key' field to appear and populating this gives an App Key that can be used successfully for an OTAA join.

![image](https://user-images.githubusercontent.com/2385623/51553653-489b9300-1e6b-11e9-8261-017389e53af2.png)

This of course means that we end up with multiple devices associated with the same App EUI but different App Keys. I assume that OK...

**Comment by jw35** [comment]
The loraWAN spec (at least v1.0) confirms, rather confusingly, that

>The AppKey is an AES-128 application key *specific for the end-device* that is assigned by
19 the application owner to the end-device 

v1.1 seems to have made some changes in this area :-(

**Comment by jw35** [comment]
FWIW ABP seems to work as expected.

**Comment by abrahammartin** [comment]
Not sure where the problem is in (1)

> 1. In a client, an OTAA registration needs a `Dev EUI`, an `App EUI` and and `App Key`. On the CSN device page you get to supply and/or generate a Dev EUI and an App Key, but there's no reference to an App EUI.

In the form, the user has to select the CSN Application, that is the App EUI. As with the Dev EUI, these are just unique identifiers of the device or de applicaiton. We don't send that App EUI to Everynet, instead we send the Everynet Vertex App EUI as we need this to be able to proxy the data back to the user.

> 2. The App Key that you supply or generate never turns up on the Everynet console. This may be because created devices have an 'Encryption' setting of 'App'.

NS encryption means that is the Network Server who does the decryption of the message, APP encryption means that is the end LoRaWAN application the one that will do the decryption. In the past, everynet used to have both, the network server and the LoRaWAN application (via lora.run), so this option was not available as it didn't matter, one or other piece of everynet would end up doing the decryption. Now this is different, with NS everynet does the decryption of the message and thus it needs to know the application session key and the network session key if ABP is used or these and also the application key if OTAA is used. 

Now everynet does not support lorawan application anymore in their cloud service and instead they use connections where to send the data to and is expected that this connections have the lorawan application in the other end. That means that APP encryption is now outside everynet and thus, everynet doesn't need to know about any of the encryption keys. The messages will always navigate encrypted through the whole everynet. That's why when selecting APP the keys input fields disappear. 

I have created this PR https://github.com/SmartCambridge/tfc_web/pull/281 to only support NS by now until we do a larger refactor to support APP

> This of course means that we end up with multiple devices associated with the same App EUI but different App Keys. I assume that OK...

I can't think of any reason why not.

**Comment by jw35** [comment]
> > 1. The App Key that you supply or generate never turns up on the Everynet console. This may be because created devices have an 'Encryption' setting of 'App'.
> 
> NS encryption means that is the Network Server who does the decryption of the message, APP encryption means that is the end LoRaWAN application the one that will do the decryption. In the past, everynet used to have both, the network server and the LoRaWAN application (via lora.run), so this option was not available as it didn't matter, one or other piece of everynet would end up doing the decryption. Now this is different, with NS everynet does the decryption of the message and thus it needs to know the application session key and the network session key if ABP is used or these and also the application key if OTAA is used.
> 
> Now everynet does not support lorawan application anymore in their cloud service and instead they use connections where to send the data to and is expected that this connections have the lorawan application in the other end. That means that APP encryption is now outside everynet and thus, everynet doesn't need to know about any of the encryption keys. The messages will always navigate encrypted through the whole everynet. That's why when selecting APP the keys input fields disappear.

I'm a tad lost here. partly because I don't know which version(s) of LoraWAN we are trying to support. It doesn't look to me as if you can separate the Network Server and the Application in the way you describe in LoraWAN 1.0 so I'm assuming Everynet (and so us) must be supporting a later version. I'll do some more reading.

**Comment by jw35** [comment]
Main issue resolved by #281. This is in any case moot given that we seem to be moving away from using Everynet.
